# ************************************************************
# Sequel Pro SQL dump
# Version 4541
#
# http://www.sequelpro.com/
# https://github.com/sequelpro/sequelpro
#
# Host: 127.0.0.1 (MySQL 5.7.29)
# Database: trots
# Generation Time: 2020-09-23 16:07:50 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table projects
# ------------------------------------------------------------

DROP TABLE IF EXISTS `projects`;

CREATE TABLE `projects` (
  `project_id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(300) NOT NULL,
  `description` text NOT NULL,
  `photo` varchar(300) NOT NULL,
  `specialisation` varchar(60) NOT NULL,
  `course` varchar(60) NOT NULL,
  `year` int(11) NOT NULL,
  `students` varchar(300) NOT NULL,
  `slug` varchar(300) DEFAULT '',
  `tags` varchar(300) DEFAULT NULL,
  `technologies` varchar(300) DEFAULT NULL,
  `creation_date` datetime DEFAULT NULL,
  PRIMARY KEY (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE `projects` DISABLE KEYS */;

INSERT INTO `projects` (`project_id`, `title`, `description`, `photo`, `specialisation`, `course`, `year`, `students`, `slug`, `tags`, `technologies`, `creation_date`)
VALUES
	(3,'Diabeasy','Opdracht: bedenk, ontwerp en maak een prototype van een smartwatch- en een smartphone-app, en maak er een promowebsite voor.<br><br>Diabeasy is een app voor diabetici die ervoor moet zorgen dat mensen met diabetes gedurende de hele dag een constante bloedsuikerspiegel hebben en het aantal insuline-injecties zo minimaal mogelijk kunnen houden.','https://www.gdm.gent/trots/assets/projects/diabeasy/ontwerp-website.png','CMO','NMD III',2017,'Stijn Gevens, Julie De Clerq','diebeazy','UX','Adobe XD','2017-10-04 14:37:00'),
	(8,'Parkspot 3.0','“De challenge bestaat erin om vrije parkeerplekken te herkennen binnen een stad m.b.v. hardware en software. Parkeren in een stad is een groot probleem, accurate informatie over vrije parkeerplaatsen is niet voorhanden. Auto’s rijden onnodig rond op zoek naar een parkeerplek, wat zorgt voor extra druk verkeer en CO2-uitstoot.”','https://dl.airtable.com/.attachments/c18c8ea4f8829a600fe0c82deb7639a6/10e32afd/case_parkspot.PNG','NMD','Mobile Development II',2018,'Nawang Tendar, Kevin Leemans, Jan Temmerman','parkspot-3.0','App Development, Artificial Intelligence','react native, mongodb, nodejs','2020-10-04 14:37:00'),
	(9,'Artevelde Institutional Repository','Aire is de online repository van de Arteveldehogeschool. Het is een doorzoekbaar archief gevuld met publicaties van (oud-)studenten, docenten, onderzoekers, diensten of externe partners van de Arteveldehogeschool. Aire streeft naar Open Access, zodat de publicaties zo veel mogelijk vrij toegankelijk zijn.','https://dl.airtable.com/.attachments/fe2f1c4afa2ce732f257ee24044b8860/91b88b48/case_sm_aire_mockup.jpg','GMB CM','Studio GDM',2018,'Nomi Van Gool','artevelde-institutional-repository','User Interface Design, User Experience Design','Adobe XD','2020-10-04 14:37:00'),
	(10,'Cesar','De briefing van deze opdracht voor het vak \'2D Animatie\' luidde als volgt: maak een one minute video door gebruik te maken van ‘Vormator’ elementen.','https://dl.airtable.com/.attachments/6d854a15130f8e5420c7b781175fab97/10755d82/case_cesar.png','AVD','Bachelorproef',2018,'Victor Gouhie','cesar','Motion Graphics','Adobe After Effects','2020-10-04 14:45:00'),
	(11,'Marsman','Opdracht: \'stel je voor dat een reis naar de planeet Mars even gewoon zou zijn als een intercontinentale vlucht op aarde. Hoe zou je deze reis dan promoten?\'','https://dl.airtable.com/.attachments/e3981d036e17ee706dc5b7300fd28bb2/8dc57d28/case_marsman.jpg','CMO GD','Graphic Design IV',2018,'Kato Janssens','marsman','Brand Design','Adobe Illustrator','2020-11-04 08:45:00'),
	(12,'Hackaton-week New Media Development','Hackaton-week New Media Development','https://dl.airtable.com/.attachments/7d28677d72e3f732bbdc3a441a36a187/61988c5e/hackathon.jpg','NMD','Mobile Development II',2018,'2NMD','hackaton-week-new-media-development','Hackathon, Webdevelopment, App Development','react, react native, Node.js','0000-00-00 00:00:00'),
	(13,'Web App - Swappit','Swappit is een veilingsplatform voor festivaltickets dat kopers en verkopers in contact brengt. Dit platform garandeert dat de gebruiker zijn ticket kan ruilen op een veilige en eenvoudige manier. De backoffice, gemaakt in Laravel, haalt data op uit een MySQL database en verdeelt dit via een eigen API. Via deze API consumeren we data in de frontoffice, die gemaakt is in Angular.','https://dl.airtable.com/.attachments/8c42c1ccf8ef2980be7abe89a6403f59/3286188b/case_lg_swapit_tiles.jpg','NMD','Web Development II',2018,'Jordy Van der Haegen','web-app---swappit','Webdevelopment, Back-end Development','Laravel, MySQL','2020-11-04 19:09:00'),
	(14,'Themapark campagne','De eindopdracht van de tweede jaar CMO bestond uit het ontwikkelen van een branding voor een fictief thema-pretpark. Caroline was ambitieus en ging voor een themapark dat zich een paar mijl onder de zeespiegel bevindt.','https://dl.airtable.com/.attachments/24920262d2d9fdcc7a7545422c761361/5ddb66ae/2_detail_logovoorstudie.png','CMO GD','Graphic Design IV',2018,'Caroline Pham','themapark-campagne','Brand Design','Adobe Illustrator, Adobe InDesign','0000-00-00 00:00:00'),
	(15,'3Da03: oefening in Isometric Design','De bedoeling van deze opdracht is een \"stilleven\" te maken in Isometric Design. Ook al komt er geen \"Motion\" aan te pas, toch moet het beeld een lengte hebben van 20 seconden. Maak er een boeiende 20 seconden van waarin ik me kan verliezen in een mooie verhaallijn, strak design of fijne details.','https://dl.airtable.com/.attachments/5ad3689d8b96732f8509ae752f3edb92/7c3f26fc/projects_lg_09_3Da03_3Danim1_2017_18_Jelle_DHondt.jpg','AVD','Motion Graphics 3D I',2018,'2AVD','3da03--oefening-in-isometric-design','3D Modelling','Isometric Design, 3D Modelling','0000-00-00 00:00:00'),
	(16,'Google Online Marketing Challenge','Google voorziet een Adwords reclamebudget van 250 dollar. Hiermee bedenken en lanceren de GMB\'ers een online campagne voor een non-profit organisatie. De campagne liep over een periode van drie weken.','https://dl.airtable.com/.attachments/c58ea93ac5a07e75bf1fefc9b7f2f812/531c64f5/google-thumb.jpg','GMB CM','',2018,'3GMB','google-online-marketing-challenge','Marketing','','0000-00-00 00:00:00'),
	(17,'Ecodesign ‘Granolaverpakking’','In de les Verpakkingen krijgt het tweede jaar Grafimediabeleid een echte case: ontwerp een ecologische verpakking voor de klant ‘Wees Gegroet Granola’. Volgens ‘Design Thinking’ verdiepten ze zich eerst in de omgeving van een kind of sporter en zochten ze naar de juiste verpakkingsoplossing, die dan nog eens technologisch juist zit en duurzaam is. Op de foto’s zie je het resultaat van een student.','https://dl.airtable.com/.attachments/04d934f2a7ebf4435f7a394c79ff0fa7/92cfe4ac/case_granola_3.jpg','GMB PM','Printproduction',2018,'2GMB','ecodesign-‘granolaverpakking’','Brand Design, Packaging','Verpakkingstechnologie , Ecodesign','0000-00-00 00:00:00'),
	(18,'Looking Good Krant','De selfie- en celebritycultuur drukt vandaag de dag haar stempel op een door (visuele) media doordrongen wereld en beïnvloedt onze kijk op schoonheid en esthetiek. Hiermee gingen derdejaarsstudenten Journalistiek  en studenten Graphic Design van onze opleiding aan de slag. Resultaat: een themakrant met als titel \"Looking Good\". ','https://dl.airtable.com/.attachments/c121fa2685da74a8c0c5a6efcfc82fc7/564459af/cover_2.jpg','CMO','',2018,'3GD, 3JOU','looking-good-krant','Brand Design, Magazine','','0000-00-00 00:00:00'),
	(19,'CURB Skateshop Pop Up Expo','Laatstejaars Graphic Designers van Arteveldehogeschool ontwerpen 20 skateboards voor de Gentse Curb skateshop. Één student won met haar  ontwerp de wedstrijd en haar skateboard zal effectief verkocht worden. Alle 20 ontwerpen hingen twee weken tentoon in het Gentse café Flagent. \n\nHet Nieuwsblad interviewde docent Stijn Anseel over dit project. ','https://dl.airtable.com/.attachments/9447a5a0ff88b4c15f0092f0163d15e1/428f10c7/curb-postermockup.jpg','CMO','',2018,'3GD','curb-skateshop-pop-up-expo','Brand Design','','0000-00-00 00:00:00'),
	(20,'Gravity Poster contest','Studenten Crossmedia-ontwerp kaapten goud en zilver weg tijdens de posterwedstrijd in De Winkelhaak georganiseerd door grafische bedrijven The Navigator, Soporset en Igepa. De wedstrijd ging tussen onze studenten en studenten van de AP Hogeschool Antwerpen. De roze affiche werd de uiteindelijke winnaar. ','https://dl.airtable.com/.attachments/6edcfa7af2fc00c9db07f0595981f5e8/fa1f2278/B_Winkelhaak_groep.jpg','CMO','',2018,'3CMO','gravity-poster-contest','Poster Design','','0000-00-00 00:00:00'),
	(21,'One Minute Festival 2019','Studenten Audiovisual Design organiseren elk jaar het One Minute Festival. Deze liveshow organiseren ze volledig zelf en wordt live uitgezonden. Studenten kunnen hun video van 1 minuut opsturen en hieruit worden verschillende winnaars gekozen onder verschillende categorieën. In 2019 was het al de tiende editie van dit festival.','https://dl.airtable.com/.attachments/390f09ce47764815c0373ff6110fe39f/97d1e2dc/88357350_2821450874557657_2180164243133825024_n.jpg','AVD','Studio GDM',2019,'1MMP, 2AVD, 3AVD','one-minute-festival-2019','Motion Graphics, Video, Audio','','0000-00-00 00:00:00'),
	(22,'Rebranding Steden','Onze opleiding telt ook enkele studieduurverkorters. Deze studenten mochten een eigen branding ontwikkelen voor een stad naar keuze. ','https://dl.airtable.com/.attachments/094cd35c1bd5ae469e89ad3426b61cef/5fbb9d9f/Geraardsbergen_SilkeDeVleeschouwer.jpg','CMO','',2019,'2CMO-STDV','rebranding-steden','Brand Design','','0000-00-00 00:00:00'),
	(23,'UZ Kinderhartfonds','Jongeren die een inspanningstest moeten afleggen kijken hier vaak tegenop. Ze weten niet wat hun te wachten staat of ze hebben het al eens gedaan en staan niet te springen om het opnieuw te doen. Men kan dit hen niet kwalijk nemen. Tijdens de inspanningstest dient men tot het fysieke uiterste te gaan, dit in combinatie met een intimiderende kamer vol met medische apparatuur zorgt er al snel voor dat de test niet als aangenaam wordt ervaren.','https://dl.airtable.com/.attachments/51f30a8dd203fb2719bcc907ee736e18/9e6fe5e9/case_sm_thumbnail.PNG','NMD','Studio GDM',2019,'3GDM','uz-kinderhartfonds','Webdevelopment, Motion Graphics, Internet of Things','Raspberry Pi, Node.js','2020-10-04 14:37:00'),
	(24,'Tutorial Nikon D610','Wout De Taeye maakte een originele tutorial voor zijn Nikon D610 camera.','https://dl.airtable.com/.attachments/5bfc6395105cd2c8b22ed093d8497132/725107fb/header_nikon_2.jpg','AVD','',2019,'Wout De Taeye','tutorial-nikon-d610','Video Tutorial','','0000-00-00 00:00:00'),
	(25,'Kortfilm Wiedersehen','Enkele AVD studenten produceerden \"Wiedersehen\", een spannende kortfilm over een drugsdealer in problemen.  ','https://dl.airtable.com/.attachments/aa4ea416bd0567cdfdb1ae81209dff96/09fc01dd/header_wiedersehen.jpg','AVD','',2019,'3AVD','kortfilm-wiedersehen','Kortfilm','','0000-00-00 00:00:00'),
	(26,'SnekTheMuseum ','Het idee voor “snek the museum” is ontstaan uit een project voor “Apps for Ghent”. Dit is een initiatief om de open-data van gent maximaal te gaan benutten en de mogelijkheden ervan bij zoveel mogelijk mensen bekend te maken. Ons idee komt voort uit een andere populaire app, “surprise.me” . Dit is een app die voor u willekeurig gaat bepalen waar u op reis gaat, net voordat u vertrekt. Wij willen iets gelijkaardig creëren, maar dan voor Gentse musea. En dit met een toffe, speelse twist die u de musea beter leert kennen!','https://dl.airtable.com/.attachments/0d8103500ae17ba6f88c2e8afb3f7611/cf7d2bef/case_mockupsnekthemuseum.jpg','NMD','Mobile Development II',2019,'Pieter Vleminckx, Jérôme Laroy, Nick Boone','snekthemuseum-','App Development, Webdevelopment','react native, react, mongodb, firebase, Node.js, redux','0000-00-00 00:00:00'),
	(27,'Kortfilm TEMST','Moord, drugs en corrupte agenten. Daarover gaat de fictieve kortfilm \'Temst\' van AVD-student Soufian Toté. Hij regiseerde de spannende kortfilm voor zijn eindwerk. Op Youtube werd zijn kortfilm al meer dan 6000 keer bekeken!','https://dl.airtable.com/.attachments/ec53011e804eafb91cbe192c0840f647/4b5dabf0/header_TEMST.JPG','AVD','',2019,'Soufian Toté','kortfilm-temst','Kortfilm','','0000-00-00 00:00:00'),
	(28,'Project Shrinksleeves','In het derde jaar GMB Printmedia verdiepen de studenten zich ondermeer in verpakkingstechnologie. In een realistische case wordt samengewerkt met professionelen uit het werkveld. Ze ontwerpen een eigen flesje in 3D en printen het ook driedimensionaal. Met gespecialiseerde software compenseren ze het krimpgedrag van een shrinksleeve, zodat hun design perfect op het flesje past. Uiteindelijk maken ze een prototype, zowel digitaal als een tastbaar exemplaar. ','https://dl.airtable.com/.attachments/0d7a68203605a7fbdab5ce99d3a8129a/c8f621e0/_DSC004506.JPG','GMB PM','Project Printmedia',2019,'3GMB Printmedia','project-shrinksleeves','Packaging Technology','Blender, 3D-print, Packaging Software, 3D-prototyping, Digitaal drukken op shrinksleeves','0000-00-00 00:00:00'),
	(29,'Shop The Dot','Hoe verander je de mindset bij jongeren om meer duurzaam te leven? Met die vraag gingen enkele studenten van de opleiding aan de slag tijdens het internationale project Creative Skills 21. Het slimme resultaat: Shop The Dot! ','https://dl.airtable.com/.attachments/565ab49a2e38df84ea96088504ee24fe/0b6d394b/89382881_1159010554430995_6611511896992299664_n.jpg','NMD, CMO','',2019,'Jana Bruggeman, Maarten Luyckx, Margot Serpentier, Jef Vermeire, Hans Vertriest, Maarten Oste','shop-the-dot','Webdevelopment, User Interface Design','','0000-00-00 00:00:00'),
	(30,'Crossmediatechnologie','De eerstejaars van de afstudeerrichting Grafimediabeleid en de opleiding International Graphic and Digital Media maakten kennis met 3D-technologie en audiovisuele technieken. Dat deden ze in teken van het vak Crossmediatechnologie. Hiervoor gebruikten ze Blender, Adobe Dimension, Mixamo, Aero, Première en Augment. Hun resultaten zie je in deze video. ','https://dl.airtable.com/.attachments/68e5c3b84a4cd6e7bce3015eeb862ec3/10fdf0ba/gmt_showcase.JPG','GMB','crossmediatechnologie',2019,'1GMB','crossmediatechnologie','Showcase','Blender, Adobe Dimension, Mixamo, Aero, Première, Augment','2020-12-06 08:18:00'),
	(31,'Parkeer Nu!','Hoe kunnen we de toeristen\noptimaal gebruik laten maken\nvan de beschikbare\nparkeerplaatsen in stad Gent?\n\nSamen bedachten de studenten de Parkeer Nu-applicatie en testen hun applicatie aan de hand van een wireflow. Daarna werkten ze elk een User Interface Design uit voor hun applicatie.','https://dl.airtable.com/.attachments/525b8a31d93ffa7a157affa4f84f5d4e/0234518f/Mockup_ParkeerNU.jpg','CMO','UI/UX Design III',2019,'Callebaut Valentine, Marthe Bulcke, Manon Reyntjens, Tilde Ronsse','parkeer-nu-','UI, UX, Design Thinking, App','Adobe XD','2020-12-06 13:08:00'),
	(32,'Eventapp Ghent','Hoe kunnen we promotie maken voor evenementen in Gent.','https://dl.airtable.com/.attachments/481f4c3a1b28866a5d31d3dbf43d94ee/d9c96374/mockup.jpg','CMO','UI/UX Design III',2019,'De Vreker Amber','eventapp-ghent','UI, UX, Design Thinking, App','Adobe XD','2020-12-06 13:09:00'),
	(33,'Jouw bibliotheek altijd op zak!','Hoe kunnen we het uitleenproces vereenvoudigen/\nversnellen en het assortiment\ngroter laten lijken in de Krook?','https://dl.airtable.com/.attachments/eef314a66212bae0a6c7c321f2258923/2ff6fd2c/Mockup_Krook_Application-2.png','CMO','UI/UX Design III',2019,'Emma Van der Haeghen','jouw-bibliotheek-altijd-op-zak-','UI, UX, Design Thinking, App','Adobe XD','0000-00-00 00:00:00'),
	(34,'ShareTevelde','Hoe kunnen we in tijden van corona aan de hand van een webapplicatie toch','https://dl.airtable.com/.attachments/2e7bdd9a37dc4a4242ecc8e1f35b0ddc/fdd1ad46/Screenshot_2020-05-24ReactApp4.png','NMD','Mobile Development II',2019,'Hans Vertriest','sharetevelde','Webdevelopment, App Development','JavaScript, react, Node.js, mongodb, Express','0000-00-00 00:00:00'),
	(35,'Deal the Meal','Deal the Meal is een website waarop mensen eten (al dan niet gratis) kunnen aanbieden aan buren/mensen in de omgeving. Dit kan gaan om resten, eten dat ze niet lekker vinden, zelfgemaakt eten, etc.','https://dl.airtable.com/.attachments/b90343caf3b3a11c4f2acaa6a288cfb3/0c78152c/Results1.jpg','NMD','Mobile Development II',2019,'Thomas Van de Velde','deal-the-meal','Webdevelopment, App Development','JavaScript, react, Node.js, Expree, mongodb','0000-00-00 00:00:00'),
	(36,'Switch Shop','Switch Shop is een commerciële\nsite die gebouwd is met de\npopulairste technologieën. Zo\ngebruiken we ExpressJs als\nframework voor alle user\nrequests te verwerken, en dankzij\nReact kunnen we deze applicatie\nopbouwen uit verschillende\ncomponenten, zodat deze makkelijk te onderhouden is.','https://dl.airtable.com/.attachments/96287a1eb8d70b7ef3c3f229fc3239ad/f89327c8/Screenshot12_small.png','NMD','Mobile Development II',2019,'Arne Six','switch-shop','Webdevelopment, App Development','JavaScript, react, Node.js, Express, mongodb','0000-00-00 00:00:00'),
	(37,'Skive','Skive is een platform waar muziekfanaten hun favoriete muziek kunnen delen','https://dl.airtable.com/.attachments/701dd616bd7a4a4298b077b9c79ffe56/15aeeb50/Schermafbeelding2020-05-16om09.47.11.png','NMD','Mobile Development II',2019,'Jens Deryckere','skive','Webdevelopment, App Development','JavaScript, react, Node.js, Express, mongodb','0000-00-00 00:00:00'),
	(38,'Moodcam','Gezichtsherkenning, emoties herkennen en objecten detectie.','https://dl.airtable.com/.attachments/8c9b61a2820b292eb4ecac04f370cd1d/26aeeec5/moodcam_1.JPG','NMD','Web of Things',2019,'Anna De langhe, Nawang Tendar','moodcam','Webdevelopment, Internet of Things','react, Node.js, Python, Face API, Tensorflow, firebase','0000-00-00 00:00:00'),
	(39,'One Minute Festival 2020','Het One Minute Festival is een gratis kortfilmfestival waar de 50 beste filmpjes van studenten Grafische en Digitale Media aan de Arteveldehogeschool worden vertoond. Dat gebeurt elk jaar via een live show, gepresenteerd door studenten Audiovisual Design en studenten Journalistiek. Er zijn verschillende categorieën waar prijzen gewonnen kunnen worden: originaliteit, humor, geluid, story, animatie, More than One Minute (M-O-M), etc.','https://dl.airtable.com/.attachments/441cac5f843043bd108b164cf4e3010e/25e47a4c/nieuwsbriefstudenten.jpg','AVD','Studio GDM',2020,'2AVD, 3AVD, 1AVD','one-minute-festival-2020','Video, Audio, liveshow','','0000-00-00 00:00:00'),
	(40,'Bongiorno','Opdracht: ontwikkel de rebranding van een streekproduct. Studente Graphic Design Laure Reyné nam Bongiorno Limoncello onder handen. ','https://dl.airtable.com/.attachments/c36bbf7d6c960900eb7006a230c0f4bb/8238b413/image_REYNE_LAURA_GD_Limoncello8_006.jpg','CMO GD','Graphic Design III',2020,'Laura Reyné','bongiorno','Brand Design','','0000-00-00 00:00:00'),
	(41,'Caseificio_v\'al_d\'aspa','Rebranden van een streekproduct','https://dl.airtable.com/.attachments/db600b52e8017bf2dfb793109c54cc9d/5615a5c9/image_Poster_010.jpg','CMO GD','Graphic Design III',2020,'Raven Van Daal','caseificio_v-al_d-aspa','Brand Design','','0000-00-00 00:00:00'),
	(42,'TrungNguyenCoffee','Opdracht: ontwikkel de rebranding van een streekproduct. Studente Graphic Design Emily Schmitz ontwikkelde een nieuwe look voor koffiemerk Trung Nguyen. ','https://dl.airtable.com/.attachments/d15b181fab6021b6cbc4be4cc4d05626/66f7b004/image_SchmitzEmily_BEURSWAND_015.jpg','CMO GD','Graphic Design III',2020,'Emily Schmitz','trungnguyencoffee','Brand Design','','0000-00-00 00:00:00'),
	(43,'Rebranding Mondo Nougat','Rebranden van een streekproduct: studente ontwierp deze rebranding voor Mondo Nougat. ','https://dl.airtable.com/.attachments/c7710a9a9172c10ec24af248d34952b5/f3e931c7/image_Tamsin_Franne_Advertentie_022.jpg','CMO GD','Graphic Design III',2020,'Franne Tamsin','rebranding-mondo-nougat','Brand Design','','0000-00-00 00:00:00'),
	(44,'Rebranding Yüm','Opdracht: Rebranden van een streekproduct. Studente Xandrine Lorré nam het merk Yüm onder handen. ','https://dl.airtable.com/.attachments/a93c58003d7191230c94e14f02a9abad/43ebcd76/image_Extra_caravan_031.jpg','CMO GD','Graphic Design III',2020,'Xandrine Lorré','rebranding-yüm','Brand Design','','0000-00-00 00:00:00'),
	(45,'GDM-gazet 2020','Studenten Grafische en Digitale Media maakten samen 3 edities van de GDM-gazet in het academiejaar 2019-2020. Ze interviewden docenten, studenten en mensen uit het werkveld. Studenten van alle afstudeerrichtingen werkten hieraan samen. \nDisclaimer: Deze gazet werd ontwikkeld voor de lockdown dus niet alle artikels zijn up-to-date.\nLees alle edities hier: https://issuu.com/madebygdm','https://dl.airtable.com/.attachments/ee01ff1fe4874f28da794e0e8b0ccf55/2a7ce0ab/Editie3_groep_BANNER.jpg','ALL','Studio GDM',2020,'3GDM','gdm-gazet-2020','Brand Design, Magazine, Poster Design','','0000-00-00 00:00:00'),
	(46,'Verpakking: Gin','Ontwerp de vormgeving/etiketten voor een fles gin naar keuze. Je vindt hiervoor een nieuw merk uit met zijn eigen kwaliteiten.\n\nHet etiket is het visitekaartje van de gin. Het moet er niet alleen mooi uitzien, het moet ook in weinig termen de consument uitsluitsel geven over de herkomst, de classificatie en de bijzondere eigenschappen van de gin.','https://dl.airtable.com/.attachments/9149003e387cc7c4e6cc6e8a06e19d95/72454b0e/image_debeirhannah_8012_765966_HannahDeBeir_Gekleurdeachtergrond1_002.jpg','CMO PD','Photo Design II',2020,'3CMO, 2CMO-STDV','verpakking--gin','Package Design, Cardboard Wardrobe','','0000-00-00 00:00:00'),
	(47,'Magazine, jaarverslag en catalogus','Maak een boeiend ontwerp voor een magazine, jaarverslag, catalogus, ... We staan open voor jouw suggestie!\n\n\nHet resultaat van deze opdracht is een uitgebreid ontwerp waarmee je je concept en vormgeving duidelijk kan tonen aan de klant. (Wat doe je met afbeeldingen, tabellen, grafieken, kaarten, lange teksten, infotekstjes, …) Je kiest dus zelf hoeveel pagina’s je presenteert! Doorheen je vormgeving is er duidelijk een verhaal/rode lijn voelbaar. Je kan dus continuïteit doorheen het jaarverslag garanderen. Denk na over formaat, papier, afwerking, bindwijze, … De klant heeft hier heel wat budget voorover!','https://dl.airtable.com/.attachments/65abd6a5952f66420d032b0a2f0a59fe/35d4e7b2/image_ddd_BogaertsNele_1912150001_-2_007.jpg','CMO PD','Photo Design II',2020,'Nele Bogaerts','magazine--jaarverslag-en-catalogus','Schetsen, Graphic Design, Photography, Layout','','0000-00-00 00:00:00'),
	(48,'Kijkplaat: Disect','Wat als je van alles wat je zag zonder problemen een doorsnede zou kunnen maken? Aan jou om een leuk/boeiend/inspirerend/poëtisch/creatief beeld te maken waarin je heel wat details toont aan de hand van een doorsnede.\n\n\n\nJe zorgt voor een boeiende inhoud, een spetterende lay-out en een zéér geloofwaardige fotomontage. Zorg voor voldoende diepte en diepgang. In het beeld verweef/verwerk je een sprekende zelf gekozen titel. Je plaatst minstens 5 verwijzingen in infographic style naar bepaalde onderdelen van je beeld. Er is duidelijk minstens één persoon aanwezig in je beeld. Deze persoon staat voldoende groot en zichtbaar in je beeld. Deze persoon fotografeer je in studio om een zo kwalitatief mogelijk beeld te krijgen.','https://dl.airtable.com/.attachments/6a08a898972a81616d2fe7342fb624b3/453750fb/image_VermandereFloor_kijkplaat_015.jpg','CMO PD','Photo Design II',2020,'3CMO, 2CMO-STDV','kijkplaat--disect','Schetsen, Graphic Design, Photography, Layout','','0000-00-00 00:00:00'),
	(49,'Wandbekleding SCKRPNCH','Sucker Punch Skate Shop vraagt ons om enkele coole graphics te maken voor hun winkel.\n\nDompel jezelf onder in de wereld van Roller Derby (♀/♂), rolschaatsen, roller disco, inline-skaten, ... en maak een killer graphic voor één van de muren van SCKRPNCH! Vermijd cliché\'s! \nGa gerust langs om de sfeer op te snuiven! Spreek onderling af: zorg ervoor dat je voldoende inspirerende foto\'s hebt en voldoende beeldmateriaal hebt om mock-ups te maken!\nEr zijn twee muren die je kan gebruiken. Deze muren bevinden zich vlak aan de inkom aan de linker- en rechterzijde.\n\n','https://dl.airtable.com/.attachments/72cae64e1429a34dfe4f972a3597aabd/f9f30725/VermandereFloor_sckrpnch_mockup3.jpg','CMO PD','Photo Design II',2020,'3CMO, 2CMO-STDV','wandbekleding-sckrpnch','Schetsen, Graphic Design, Photography, Layout','','0000-00-00 00:00:00'),
	(50,'The Showroom','Eindopdracht: futuristische store in een virtuele driedimensionale, interactieve wereld. Alle 3D-assets zijn zelf gemodelleerd.','https://dl.airtable.com/.attachments/9dee989c9f93c5ed2733846b0f7bbaa3/fdd14ca4/mixed-reality-2019-2020_The-Showroom.png','NMD','Mixed Reality',2020,'3NMD','the-showroom','Extended Reality, Virtual Reality, 3D Modelling','HTML, CSS, JavaScript, A-Frame, Three.js, Blender, Git, GitHub, GitHub Pages','0000-00-00 00:00:00'),
	(51,'Hello WebVR!','Eindopdracht: futuristische store in een virtuele driedimensionale, interactieve wereld. Alle 3D-assets zijn zelf gemodelleerd.','https://dl.airtable.com/.attachments/cc9ed3fd1dd12b591e04bf42e9b39015/3eeb5c47/mixed-reality-2019-2020_Hello-WebVR_01.png','NMD','Mixed Reality',2020,'3NMD','hello-webvr-','Extended Reality, Virtual Reality, 3D Modelling','HTML, CSS, JavaScript, A-Frame, Three.js, Blender, Git, GitHub, GitHub Pages','0000-00-00 00:00:00'),
	(52,'Virtuele Campus','Eindopdracht: Arteveldehogeschool Campus Mariakerke in een virtuele, driedimensionale wereld. Alle 3D-assets zijn zelf gemodelleerd.','https://dl.airtable.com/.attachments/adf3431d24498da1d75b548422ce9669/75f0f611/mixed-reality-2018-2019_Virtuele-Campus_01.png','NMD','Mixed Reality',2020,'3NMD','virtuele-campus','Extended Reality, Virtual Reality, 3D Modelling','HTML, CSS, JavaScript, A-Frame, Three.js, Blender, Git, GitHub, GitHub Pages, AngularJS','0000-00-00 00:00:00'),
	(53,'404-Design Challenge thema Corona','): Studenten kregen als rush-opdracht ( van 3 uur) een 404-pagina te ontwerpen in team met als thema corona','https://dl.airtable.com/.attachments/0b20453d11902108a1ab4eabc9e65501/3e0421ec/Tim.png','CMO','UI/UX Design III',2020,'1CMO','404-design-challenge-thema-corona','Web Design','Adobe XD','0000-00-00 00:00:00'),
	(54,'Mercury Flooring','Vormgeving van tapijten die commercieel in de markt worden gezet, de studenten worden uitgedaagd om origineel te zijn om op te vallen in een verzadigde markt! Deze opdracht vraagt veel creativiteit met toch het ook op verkoopbaarheid. ','https://dl.airtable.com/.attachments/7e27e4082270f917307ffde43b655e55/05dd5f57/MockupEaster_Artoo.jpg','CMO','Studio GDM',2020,'Artoo Guns, Sam Van Assche, Margot Gevaert, Joëlle Duran, Jordi Allard','mercury-flooring','Brand Design','','0000-00-00 00:00:00'),
	(55,'European Marine Board','Voor hun volgende conferentie gingen onze studenten aan de slag. De volledige branding is verzorgt door studenten om zo marine wetenschappen visueel aantrekkelijk te maken voor niet-wetenschappers. ','https://dl.airtable.com/.attachments/3cf563b4d87744043d513fc61a826f67/8f0c87b7/Kni2psel.JPG','CMO, NMD','Studio GDM',2020,'Jonas Willems, Christian Moraru, Maud Chiau, Paul Dekeyser','european-marine-board','Brand Design, Book, infographic, Design Thinking, Digitaal','','0000-00-00 00:00:00'),
	(56,'Landschap schetsen','Studenten 1CMO schetsten een bestaand landschap ','https://dl.airtable.com/.attachments/d534c07ff01f1cd460e4ff807c5c3cce/36b401d4/AmberTervoort-landschappen.png','CMO','',2020,'1CMO','landschap-schetsen','Schetsen','','0000-00-00 00:00:00'),
	(57,'Let\'s pretend the 60\'s never happened','Maak een superboeiende en ultra-creatieve compositie met een vette knipoog naar de jaren 60.\n\nBoeiende lay-out, typografie, samenhang - sterke blikvanger\nEr is een duidelijk tekstelement waar je heel wat werk insteekt - een korte titel. De typografie is geïntegreerd met het beeld. Beeld en typo vormen één geheel.\n\nState of the art photoshop. Licht, sfeer, schaduwen, ... ben je nu heer en meester over. Met dit werk bewijs je dat je een photoshop-pro bent!\nGebruik van rechtenvrije beelden indien je dit werkstuk wil opnemen in je portfolio.\nDe belangrijkste blikvangers heb je zelf gecreëerd. Boeiende delen detoureren en plaatsen kan iedereen.','https://dl.airtable.com/.attachments/2a2024f1d3eca26b8f1ba8d9ffd1936f/63051e54/A_3_Wils_Michiel_sm.jpg','CMO','Graphic Design II: Photoshop 2 CMO',2020,'2CMO','let-s-pretend-the-60-s-never-happened','Beeldverwerking, Beeldmanipulatie, Fotografie','Photoshop','0000-00-00 00:00:00'),
	(58,'Let\'s pretend the 80\'s never happened','Maak een superboeiende en ultra-creatieve compositie met een vette knipoog naar de jaren 80.\n\nBoeiende lay-out, typografie, samenhang - sterke blikvanger\nEr is een duidelijk tekstelement waar je heel wat werk insteekt - een korte titel. De typografie is geïntegreerd met het beeld. Beeld en typo vormen één geheel.\n\nState of the art photoshop. Licht, sfeer, schaduwen, ... ben je nu heer en meester over. Met dit werk bewijs je dat je een photoshop-pro bent!\n\nGebruik van rechtenvrije beelden indien je dit werkstuk wil opnemen in je portfolio.\n\nDe belangrijkste blikvangers heb je zelf gecreëerd. Boeiende delen detoureren en plaatsen kan iedereen.','https://dl.airtable.com/.attachments/de1192fa16970f3193b2d5eb36f03544/4a7b4a2a/A_5_Otti_Ekene_sm.jpg','CMO','Graphic Design II: Photoshop 2 CMO',2020,'2CMO','let-s-pretend-the-80-s-never-happened','Beeldverwerking, Beeldmanipulatie, Fotografie','Photoshop','0000-00-00 00:00:00'),
	(59,'Veggie-boat','Maak een krachtig campagnebeeld dat zal gebruikt worden om een vegetarische organisatie te promoten. Het concept dat hiervoor bedacht is is een groenten- en/of fruitbootje op het water. \n\nEen bootje gemaakt van groenten of fruit, Een persoon in het bootje, Een duidelijke en geloofwaardige reflectie in het water, Een brandende lantaarn,\n\nAchtergrond ondersteunt de blikvanger en leidt niet af. Zorg voor heel wat sfeer in je beeld.','https://dl.airtable.com/.attachments/2861dba0445bb1563159cb8da02a1189/6c605300/A_2_Brughmans_Karolien_sm.jpg','CMO','Graphic Design II: Photoshop 2 CMO',2020,'2CMO','veggie-boat','Beeldverwerking, Beeldmanipulatie, Fotografie','Photoshop','0000-00-00 00:00:00');

/*!40000 ALTER TABLE `projects` ENABLE KEYS */;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
